name: Docker

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  IMAGE_NAME: tor-transparent-proxy

jobs:
  test:
  
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: leleliu008/github-actions-vagrant@v1
        with:
          mem: 2048
          box: ubuntu/focal64
          run: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
            docker build . --file Dockerfile -t test-image
            IP=$(curl -s http://checkip.amazonaws.com)
            sudo modprobe nft_redir
            IP2=$(docker run --rm --cap-add=NET_ADMIN --cap-add=NET_RAW tor /bin/sh -c "sleep 20 && wget -q -O - -T 60 http://checkip.amazonaws.com")
            echo "IP of host:      $IP"
            echo "IP of container: $IP2"
            [[ "$IP" != "$IP2" ]] || exit 1

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "main" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
